name:                singletons-default
version:             0.1.0.5
github:              "morphismtech/singletons-default"
license:             BSD-3-Clause
author:              "Eitan Chatav"
maintainer:          "eitan.chatav@gmail.com"
copyright:           "2024 Eitan Chatav"
synopsis:            An optional type with type level default
category:            Data
description:         dependently typed optional values with default
extra-doc-files:
- README.md
- CHANGELOG.md
dependencies:
- base >= 4.7 && < 5
- data-default >= 0.7.1 && < 0.8
- singletons >= 3.0.2 && < 3.1
- singletons-base >= 3.1.1 && < 3.5
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
library:
  source-dirs: src
